### Metadata
GET http://localhost:4004/cv/$metadata
### Skill Groups
GET http://localhost:4004/cv/SkillGroups
### Skills
GET http://localhost:4004/cv/Skills
### Skill Groups (expand)
GET http://localhost:4004/cv/SkillGroups?$expand=skills
### Work Experience (expand)
GET http://localhost:4004/cv/WorkExperiences?$expand=company,projectRoles($orderby=order;$expand=child),responsibilities,technologies($orderby=order;$expand=child)&$orderby=ID desc